/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/P1Gat6DIy8O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Abouts() {
  return (
    <>
      <header className="w-full mx-auto  bg-white dark:bg-gray-950 shadow">
        <div className="container flex items-center justify-between h-16 px-4 md:px-6">
          <Link className="flex items-center gap-2 text-lg font-semibold" href="#">
            <CloudIcon className="h-6 w-6" />
            <span className="sr-only">D3cloud</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
            <Link className="hover:underline" href="/">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Services
            </Link>
            <Link className="hover:underline" href="#">
              Pricing
            </Link>
            <Link className="hover:underline" href="/">
              About
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <Button className="hidden md:inline-flex" size="sm" variant="outline">
              Sign In
            </Button>
            <Button className="hidden md:inline-flex" size="sm">
              Get Started
            </Button>
            <Button className="md:hidden" size="icon" variant="ghost">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </div>
        </div>
      </header>
      <section className="w-full pt-12 md:pt-24 lg:pt-32">
        <header className="container space-y-10 xl:space-y-16">
          <div className="grid gap-4 px-10 md:grid-cols-2 md:gap-16">
            <div>
              <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                About D3cloud
              </h1>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Learn more about our company and our mission to transform the cloud computing landscape.
              </p>
              <div className="space-x-4 mt-6">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-blue-500 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-blue-500/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-500 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-blue-500 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Learn More
                </Link>
              </div>
            </div>
            <div className="flex flex-col items-start space-y-4">
              <img
                alt="About"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                height="550"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </header>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Story</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                D3cloud was founded in 2018 with the mission to revolutionize the cloud computing industry. Our team of
                experienced professionals has been working tirelessly to develop cutting-edge solutions that empower
                businesses of all sizes to thrive in the digital age.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <TargetIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Our Vision</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                To be the leading provider of cloud solutions that empower businesses to achieve their full potential.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <CompassIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Our Mission</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                To deliver innovative cloud solutions that drive business growth, improve operational efficiency, and
                enhance customer experiences.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <UsersIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Our Values</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Integrity, innovation, customer-centricity, and a commitment to excellence in everything we do.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Meet Our Team</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our talented and dedicated team is the driving force behind D3cloud's success.
            </p>
          </div>
          <div className="mx-auto w-full max-w-4xl space-y-6">
            <div className="grid gap-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
              <div className="flex items-center gap-4">
                <div className="rounded-full bg-gray-200 p-1 dark:bg-gray-800">
                  <img alt="Jane Doe" className="h-16 w-16 rounded-full object-cover" src="/placeholder.svg" />
                </div>
                <div>
                  <div className="font-semibold">Jane Doe</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">CEO</div>
                </div>
              </div>
              <p className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                "Our team is dedicated to delivering the best cloud solutions to our clients."
              </p>
            </div>
            <div className="grid gap-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
              <div className="flex items-center gap-4">
                <div className="rounded-full bg-gray-200 p-1 dark:bg-gray-800">
                  <img alt="John Smith" className="h-16 w-16 rounded-full object-cover" src="/placeholder.svg" />
                </div>
                <div>
                  <div className="font-semibold">John Smith</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">CTO</div>
                </div>
              </div>
              <p className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                "We're constantly innovating to stay ahead of the curve and provide our clients with the best possible
                solutions."
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Join Our Team</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                We're always looking for talented individuals to join our growing team. Check out our open positions and
                apply today!
              </p>
            </div>
          </div>
          <div className="mx-auto w-full max-w-md space-y-4">
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Enter your message" rows={5} />
              </div>
              <Button className="justify-self-end" type="submit">
                Apply
              </Button>
            </form>
          </div>
        </div>
      </section>
      <footer className="w-full bg-gray-950 text-gray-50 py-10">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-6 px-4 md:px-6">
          <div className="flex items-center gap-2">
            <MountainIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">D3cloud</span>
          </div>
          <nav className="flex flex-col md:flex-row items-center gap-4 md:gap-6 text-sm font-medium">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Services
            </Link>
            <Link className="hover:underline" href="#">
              Pricing
            </Link>
            <Link className="hover:underline" href="#">
              About
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="text-sm text-gray-400">© 2024 D3cloud. All rights reserved.</div>
        </div>
      </footer>
    </>
  )
}

function CloudIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CompassIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TargetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="6" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
