/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0toqrNApkvF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { JSX, SVGProps } from "react";

export function Kalu() {
  return (
    <>
      <header className="w-full bg-white dark:bg-gray-950 shadow">
        <div className="container flex items-center justify-between h-16 px-4 md:px-6">
          <Link className="flex items-center gap-2 text-xl font-bold" href="#">
            <CloudIcon className="h-6 w-6" />
            <span className="sr-only">D3cloud</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
            <Link className="hover:underline" href="/">
              Home
            </Link>
            <Link className="hover:underline" href="/Service">
              Services
            </Link>
            <Link className="hover:underline" href="/Price">
              Pricing
            </Link>
            <Link className="hover:underline" href="/About">
              About
            </Link>
            <Link className="hover:underline" href="/Contact">
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            {/* <Button className="hidden md:inline-flex" size="sm" variant="outline">
              Sign In
            </Button> */}
            <Button className="hidden md:inline-flex" size="sm">
              Get Started
            </Button>
            <Button className="md:hidden" size="icon" variant="ghost">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </div>
        </div>
      </header>
      <section className="w-full pt-12 md:pt-24 lg:pt-32">
        <header className="container items-center justify-between space-y-10 2xl:space-y-16">
          <div className="grid gap-4 px-12 md:grid-cols-2 md:gap-16">
            <div>
              <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                D3cloud
              </h1>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Elevate your digital presence with our cutting-edge cloud solutions.
              </p>
              <div className="space-x-4 mt-6">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-blue-500 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-blue-500/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-500 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-blue-500 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Get Started
                </Link>
              </div>
            </div>
            <div className="flex flex-col items-start space-y-4">
              <img
                alt="Hero"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                height="550"
                src="/placeholder.svg"
                width="550"
              />
            </div>
          </div>
        </header>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Our Key Services</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Discover how D3cloud can transform your business with our innovative cloud solutions.
              </p>
            </div>
          </div>
          <div className="mx-auto grid items-start gap-8 sm:max-w-4xl sm:grid-cols-2 md:gap-12 lg:max-w-5xl lg:grid-cols-3">
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <CloudIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Cloud Solutions</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Leverage the power of the cloud to scale your business and unlock new opportunities.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <DatabaseIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Data Management</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Securely store, manage, and analyze your data with our robust data management solutions.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <CodeIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">DevOps Automation</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Streamline your development and deployment processes with our cutting-edge DevOps solutions.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <CpuIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Serverless Computing</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Simplify your infrastructure and focus on your core business with our serverless computing solutions.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <NetworkIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Networking Solutions</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Optimize your network infrastructure and ensure reliable connectivity with our networking solutions.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <LockIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Cybersecurity</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Protect your business from cyber threats with our comprehensive security solutions.
              </p>
            </div>
            <div className="grid gap-1">
              <div className="flex items-center gap-3">
                <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                  <HandHelpingIcon className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold">Managed Services</h3>
              </div>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Leverage our expert team to manage your IT infrastructure and operations, freeing you to focus on your
                core business.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">What Our Customers Say</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Hear from our satisfied customers and see how D3cloud has helped their businesses thrive.
            </p>
          </div>
          <div className="mx-auto w-full max-w-4xl space-y-6">
            <div className="grid gap-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
              <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                "D3cloud has been a game-changer for our business. Their cloud solutions have helped us scale our
                operations and improve our efficiency."
              </blockquote>
              <div>
                <div className="font-semibold">Jane Doe</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">CEO, Acme Inc</div>
              </div>
            </div>
            <div className="grid gap-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
              <blockquote className="text-lg font-semibold leading-snug lg:text-xl lg:leading-normal xl:text-2xl">
                "I was hesitant to migrate to the cloud, but D3cloud made the process seamless. Their team of experts
                guided us every step of the way."
              </blockquote>
              <div>
                <div className="font-semibold">John Smith</div>
                <div className="text-sm text-gray-500 dark:text-gray-400">CTO, Globex Corporation</div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container space-y-12 px-4 md:px-6">
          <div className="flex flex-col items-center justify-center space-y-4 text-center">
            <div className="space-y-2">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Contact Us</h2>
              <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Get in touch with our team to learn more about our cloud solutions.
              </p>
            </div>
          </div>
          <div className="mx-auto w-full max-w-md space-y-4">
            <form className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="Enter your email" type="email" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="message">Message</Label>
                <Textarea id="message" placeholder="Enter your message" rows={5} />
              </div>
              <Button className="justify-self-end" type="submit">
                Submit
              </Button>
            </form>
          </div>
        </div>
      </section>
      <footer className="w-full bg-gray-950 text-gray-50 py-10">
        <div className="container flex flex-col md:flex-row items-center justify-between gap-6 px-4 md:px-6">
          <div className="flex items-center gap-2">
            <MountainIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">D3cloud</span>
          </div>
          <nav className="flex flex-col md:flex-row items-center gap-4 md:gap-6 text-sm font-medium">
            <Link className="hover:underline" href="#">
              Home
            </Link>
            <Link className="hover:underline" href="#">
              Services
            </Link>
            <Link className="hover:underline" href="#">
              Pricing
            </Link>
            <Link className="hover:underline" href="#">
              About
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="text-sm text-gray-400">© 2024 D3cloud. All rights reserved.</div>
        </div>
      </footer>
    </>
  )
}

function CloudIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function CodeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  )
}


function CpuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="16" x="4" y="4" rx="2" />
      <rect width="6" height="6" x="9" y="9" rx="1" />
      <path d="M15 2v2" />
      <path d="M15 20v2" />
      <path d="M2 15h2" />
      <path d="M2 9h2" />
      <path d="M20 15h2" />
      <path d="M20 9h2" />
      <path d="M9 2v2" />
      <path d="M9 20v2" />
    </svg>
  )
}


function DatabaseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function HandHelpingIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 12h2a2 2 0 1 0 0-4h-3c-.6 0-1.1.2-1.4.6L3 14" />
      <path d="m7 18 1.6-1.4c.3-.4.8-.6 1.4-.6h4c1.1 0 2.1-.4 2.8-1.2l4.6-4.4a2 2 0 0 0-2.75-2.91l-4.2 3.9" />
      <path d="m2 13 6 6" />
    </svg>
  )
}


function LockIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}


function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function NetworkIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="16" y="16" width="6" height="6" rx="1" />
      <rect x="2" y="16" width="6" height="6" rx="1" />
      <rect x="9" y="2" width="6" height="6" rx="1" />
      <path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3" />
      <path d="M12 12V8" />
    </svg>
  )
}
